return {
    Title = "Dominant",
    Version = "2.0.0",
    Folder = "Dominant",
    SettingsFile = "Dominant/session.json",
    Theme = "Dark",
    KeyTheme = "Dark",
    Logo = "rbxassetid://116590139091461",
    VindUrl = "https://raw.githubusercontent.com/Skinny-yz/vindUI-Test/main/full.luau",
    OphynUrl = "https://ophyn.space/interface",
    Keys = { "dominant", "arroganthi", "1234" },
    SaveKey = false,
    Discord = "discord.gg/yourcode",
    Website = "https://example.com",
}
