-- Translations for the window background (shared by every game).
return {
    en = {
        bg_applied = "Background applied",
        bg_apply = "Apply",
        bg_browse = "Browse Workspace",
        bg_browse_d = "Open Dominant/Backgrounds folder tree",
        bg_clear = "Clear Background",
        bg_enabled = "Enable Background",
        bg_failed = "Failed to load background",
        bg_folder_hint = "Put images in Dominant/Backgrounds",
        bg_gif_note = "GIF, PNG, JPG and JPEG are supported",
        bg_path = "Background Path",
        bg_refresh = "Refresh Files",
        bg_scale = "Background Scale",
        bg_transparency = "Background Transparency",
        bg_window_transparency = "Window Transparency",
        sec_background = "Background",
    },
    pt = {
        bg_applied = "Plano de fundo aplicado",
        bg_apply = "Aplicar",
        bg_browse = "Explorar Workspace",
        bg_browse_d = "Abrir árvore da pasta Dominant/Backgrounds",
        bg_clear = "Limpar Fundo",
        bg_enabled = "Ativar Plano de Fundo",
        bg_failed = "Falha ao carregar o fundo",
        bg_folder_hint = "Coloque imagens em Dominant/Backgrounds",
        bg_gif_note = "GIF, PNG, JPG e JPEG são suportados",
        bg_path = "Caminho do Fundo",
        bg_refresh = "Atualizar Arquivos",
        bg_scale = "Escala do Fundo",
        bg_transparency = "Transparência do Fundo",
        bg_window_transparency = "Transparência da Janela",
        sec_background = "Plano de Fundo",
    },
    es = {
        bg_applied = "Fondo aplicado",
        bg_apply = "Aplicar",
        bg_browse = "Explorar Workspace",
        bg_browse_d = "Abrir árbol de Dominant/Backgrounds",
        bg_clear = "Quitar Fondo",
        bg_enabled = "Activar Fondo",
        bg_failed = "Error al cargar el fondo",
        bg_folder_hint = "Pon imágenes en Dominant/Backgrounds",
        bg_gif_note = "Se admiten GIF, PNG, JPG y JPEG",
        bg_path = "Ruta del Fondo",
        bg_refresh = "Actualizar Archivos",
        bg_scale = "Escala del Fondo",
        bg_transparency = "Transparencia del Fondo",
        bg_window_transparency = "Transparencia de la Ventana",
        sec_background = "Fondo",
    },
    ru = {
        bg_applied = "Фон применён",
        bg_apply = "Применить",
        bg_browse = "Обзор Workspace",
        bg_browse_d = "Открыть дерево Dominant/Backgrounds",
        bg_clear = "Убрать фон",
        bg_enabled = "Включить фон",
        bg_failed = "Не удалось загрузить фон",
        bg_folder_hint = "Кладите изображения в Dominant/Backgrounds",
        bg_gif_note = "Поддерживаются GIF, PNG, JPG и JPEG",
        bg_path = "Путь фона",
        bg_refresh = "Обновить файлы",
        bg_scale = "Масштаб фона",
        bg_transparency = "Прозрачность фона",
        bg_window_transparency = "Прозрачность окна",
        sec_background = "Фон",
    },
}
