-- Pressure translations: English, Portuguese, Spanish and Russian.
-- Keys: tab_* tabs, sec_* sections, label keys, *_d descriptions, n_* notifications.
return {
    en = {
        pressure_version1 = "1.0.0", pressure_date1 = "2026-10-09", pressure_log1 = "ESP, anti removals, movement, automation and world tools for Pressure", pressure_log2 = "Shared Home, Settings, configs, background and translations",
        tab_visuals = "Visuals", tab_movement = "Movement", tab_automation = "Automation",
        tab_anti = "Anti", tab_world = "World", tab_misc = "Misc",
        sec_esp = "ESP", sec_esp_colors = "Colors", sec_speed = "Speed", sec_jump = "Jump",
        sec_collision = "Collision", sec_flight = "Flight", sec_teleport = "Teleport", sec_collect = "Collection",
        sec_doors = "Doors", sec_alerts = "Alerts", sec_lighting = "Lighting", sec_camera = "Camera",
        sec_utility = "Utility", sec_server = "Server", sec_anti_monsters = "Monsters",
        sec_anti_spawns = "Spawns", sec_anti_encounters = "Encounters",
        esp = "Enable ESP", esp_d = "Master switch for every ESP option",
        esp_monsters = "Monsters", esp_players = "Players", esp_items = "Items", esp_currency = "Currency",
        esp_keycards = "Keycards", esp_doors = "Exit doors", esp_lockers = "Void lockers",
        esp_fake_doors = "Good people doors", esp_generators = "Generators",
        esp_text = "Name labels", esp_distance = "Show distance", esp_max_distance = "Max distance",
        esp_fill = "Fill opacity", color_monster = "Monster color", color_player = "Player color",
        esp_exit_door = "EXIT DOOR", esp_locker = "Void Locker", esp_fake_door = "GOOD PEOPLE DOOR",
        esp_generator = "Generator %s%%",
        cframe_speed = "CFrame speed", cframe_speed_value = "Speed value", speed_boost_on = "Speed boost",
        speed_boost = "Boost amount", jumppower_on = "Custom jump power", jumppower = "Jump power",
        infinite_jump = "Infinite jump", noclip = "Noclip", ghost_players = "Ghost players",
        fly = "Fly", fly_speed = "Fly speed",
        btn_tp_nearest = "Teleport to nearest player", btn_tp_farthest = "Teleport to farthest player",
        btn_anchor_drop = "Drop anchor", btn_anchor_beam = "Beam me up",
        loot_aura = "Loot aura", loot_radius = "Loot radius", instant_prompts = "Instant prompts",
        open_sesame = "Open sesame", btn_door_yeet = "Door YEET", entity_alert = "Entity alert",
        fullbright = "Fullbright", no_fog = "Remove fog", fov_on = "Custom FOV", fov = "Field of view",
        third_person = "Third person", third_person_dist = "Camera distance",
        anti_afk = "Anti AFK", auto_rejoin = "Auto rejoin on kick", btn_rejoin = "Rejoin server",
        btn_serverhop = "Server hop", btn_copy_jobid = "Copy job ID", btn_copy_join = "Copy join script",
        btn_reset_char = "Reset character",
        anti_desc = "Removes %s",
        anti_eyefestation = "Anti Eyefestation", anti_pandemonium = "Spoof Pandemonium",
        anti_pipsqueak = "Spoof Pipsqueak", anti_a200 = "Spoof A200", anti_walldweller = "Remove WallDweller",
        anti_bouncer = "Remove Bouncer", anti_skeletonhead = "Remove skeleton head", anti_statue = "Remove statue",
        anti_nogood = "Anti NoGood", anti_skinless = "Remove skinless corpse", anti_cement = "Remove cement shoes",
        anti_witchinghour = "Remove WitchingHour", anti_divine = "Anti DiVine", anti_searchlights = "Remove searchlights",
        anti_monsterlocker = "Remove monster locker", anti_turrets = "Remove turrets", anti_tripwires = "Remove tripwires",
        anti_landmines = "Remove landmines", anti_squiddles = "Anti squiddles", anti_coagulate = "Anti coagulate",
        anti_edentrees = "Remove Edentrees", anti_damageparts = "Remove damage parts", anti_firewall = "Remove firewall",
        hotkey_fly = "Fly hotkey", hotkey_noclip = "Noclip hotkey", hotkey_esp = "ESP hotkey", hotkey_panic = "Panic key",
        n_no_player = "No player found", n_anchor_set = "Anchor dropped", n_no_anchor = "No anchor saved",
        n_rooms_missing = "Rooms not found yet", n_open_sesame = "You can now walk through doors",
        n_spawned = "%s spawned!", n_panic = "Every feature was turned off", n_no_servers = "No other servers found",
        n_hopping = "Joining another server", n_rejoining = "Rejoining",
    },
    pt = {
        pressure_version1 = "1.0.0", pressure_date1 = "2026-10-09", pressure_log1 = "ESP, remoções anti, movimento, automação e ferramentas de mundo para o Pressure", pressure_log2 = "Home, Settings, configs, fundo e traduções compartilhados",
        tab_visuals = "Visuais", tab_movement = "Movimento", tab_automation = "Automação",
        tab_anti = "Anti", tab_world = "Mundo", tab_misc = "Diversos",
        sec_esp = "ESP", sec_esp_colors = "Cores", sec_speed = "Velocidade", sec_jump = "Pulo",
        sec_collision = "Colisão", sec_flight = "Voo", sec_teleport = "Teleporte", sec_collect = "Coleta",
        sec_doors = "Portas", sec_alerts = "Alertas", sec_lighting = "Iluminação", sec_camera = "Câmera",
        sec_utility = "Utilidades", sec_server = "Servidor", sec_anti_monsters = "Monstros",
        sec_anti_spawns = "Spawns", sec_anti_encounters = "Encontros",
        esp = "Ativar ESP", esp_d = "Chave geral de todas as opções de ESP",
        esp_monsters = "Monstros", esp_players = "Jogadores", esp_items = "Itens", esp_currency = "Moedas",
        esp_keycards = "Cartões-chave", esp_doors = "Portas de saída", esp_lockers = "Armários do Vazio",
        esp_fake_doors = "Portas falsas", esp_generators = "Geradores",
        esp_text = "Nomes", esp_distance = "Mostrar distância", esp_max_distance = "Distância máxima",
        esp_fill = "Opacidade do preenchimento", color_monster = "Cor dos monstros", color_player = "Cor dos jogadores",
        esp_exit_door = "PORTA DE SAÍDA", esp_locker = "Armário do Vazio", esp_fake_door = "PORTA FALSA",
        esp_generator = "Gerador %s%%",
        cframe_speed = "Velocidade CFrame", cframe_speed_value = "Valor da velocidade", speed_boost_on = "Impulso de velocidade",
        speed_boost = "Força do impulso", jumppower_on = "Pulo personalizado", jumppower = "Força do pulo",
        infinite_jump = "Pulo infinito", noclip = "Atravessar paredes", ghost_players = "Jogadores fantasma",
        fly = "Voar", fly_speed = "Velocidade de voo",
        btn_tp_nearest = "Teleportar ao jogador mais próximo", btn_tp_farthest = "Teleportar ao jogador mais distante",
        btn_anchor_drop = "Soltar âncora", btn_anchor_beam = "Voltar à âncora",
        loot_aura = "Aura de coleta", loot_radius = "Raio de coleta", instant_prompts = "Prompts instantâneos",
        open_sesame = "Abre-te sésamo", btn_door_yeet = "Porta YEET", entity_alert = "Alerta de entidade",
        fullbright = "Brilho total", no_fog = "Remover neblina", fov_on = "FOV personalizado", fov = "Campo de visão",
        third_person = "Terceira pessoa", third_person_dist = "Distância da câmera",
        anti_afk = "Anti AFK", auto_rejoin = "Reentrar ao ser expulso", btn_rejoin = "Reentrar no servidor",
        btn_serverhop = "Trocar de servidor", btn_copy_jobid = "Copiar ID do servidor", btn_copy_join = "Copiar script de entrada",
        btn_reset_char = "Resetar personagem",
        anti_desc = "Remove %s",
        anti_eyefestation = "Anti Eyefestation", anti_pandemonium = "Falsificar Pandemonium",
        anti_pipsqueak = "Falsificar Pipsqueak", anti_a200 = "Falsificar A200", anti_walldweller = "Remover WallDweller",
        anti_bouncer = "Remover Bouncer", anti_skeletonhead = "Remover cabeça de esqueleto", anti_statue = "Remover estátua",
        anti_nogood = "Anti NoGood", anti_skinless = "Remover cadáver sem pele", anti_cement = "Remover sapatos de cimento",
        anti_witchinghour = "Remover WitchingHour", anti_divine = "Anti DiVine", anti_searchlights = "Remover holofotes",
        anti_monsterlocker = "Remover armário de monstro", anti_turrets = "Remover torretas", anti_tripwires = "Remover armadilhas de fio",
        anti_landmines = "Remover minas", anti_squiddles = "Anti squiddles", anti_coagulate = "Anti coagulate",
        anti_edentrees = "Remover Edentrees", anti_damageparts = "Remover partes de dano", anti_firewall = "Remover firewall",
        hotkey_fly = "Tecla de voo", hotkey_noclip = "Tecla de atravessar", hotkey_esp = "Tecla do ESP", hotkey_panic = "Tecla de pânico",
        n_no_player = "Nenhum jogador encontrado", n_anchor_set = "Âncora salva", n_no_anchor = "Nenhuma âncora salva",
        n_rooms_missing = "Salas ainda não encontradas", n_open_sesame = "Agora você pode atravessar as portas",
        n_spawned = "%s apareceu!", n_panic = "Todas as funções foram desligadas", n_no_servers = "Nenhum outro servidor encontrado",
        n_hopping = "Entrando em outro servidor", n_rejoining = "Reentrando",
    },
    es = {
        pressure_version1 = "1.0.0", pressure_date1 = "2026-10-09", pressure_log1 = "ESP, eliminaciones anti, movimiento, automatización y herramientas de mundo para Pressure", pressure_log2 = "Home, Settings, configs, fondo y traducciones compartidos",
        tab_visuals = "Visuales", tab_movement = "Movimiento", tab_automation = "Automatización",
        tab_anti = "Anti", tab_world = "Mundo", tab_misc = "Varios",
        sec_esp = "ESP", sec_esp_colors = "Colores", sec_speed = "Velocidad", sec_jump = "Salto",
        sec_collision = "Colisión", sec_flight = "Vuelo", sec_teleport = "Teletransporte", sec_collect = "Recolección",
        sec_doors = "Puertas", sec_alerts = "Alertas", sec_lighting = "Iluminación", sec_camera = "Cámara",
        sec_utility = "Utilidades", sec_server = "Servidor", sec_anti_monsters = "Monstruos",
        sec_anti_spawns = "Apariciones", sec_anti_encounters = "Encuentros",
        esp = "Activar ESP", esp_d = "Interruptor general de todas las opciones de ESP",
        esp_monsters = "Monstruos", esp_players = "Jugadores", esp_items = "Objetos", esp_currency = "Monedas",
        esp_keycards = "Tarjetas", esp_doors = "Puertas de salida", esp_lockers = "Casilleros del Vacío",
        esp_fake_doors = "Puertas falsas", esp_generators = "Generadores",
        esp_text = "Nombres", esp_distance = "Mostrar distancia", esp_max_distance = "Distancia máxima",
        esp_fill = "Opacidad del relleno", color_monster = "Color de monstruos", color_player = "Color de jugadores",
        esp_exit_door = "PUERTA DE SALIDA", esp_locker = "Casillero del Vacío", esp_fake_door = "PUERTA FALSA",
        esp_generator = "Generador %s%%",
        cframe_speed = "Velocidad CFrame", cframe_speed_value = "Valor de velocidad", speed_boost_on = "Impulso de velocidad",
        speed_boost = "Cantidad de impulso", jumppower_on = "Salto personalizado", jumppower = "Fuerza del salto",
        infinite_jump = "Salto infinito", noclip = "Atravesar paredes", ghost_players = "Jugadores fantasma",
        fly = "Volar", fly_speed = "Velocidad de vuelo",
        btn_tp_nearest = "Teletransportar al jugador más cercano", btn_tp_farthest = "Teletransportar al jugador más lejano",
        btn_anchor_drop = "Soltar ancla", btn_anchor_beam = "Volver al ancla",
        loot_aura = "Aura de recolección", loot_radius = "Radio de recolección", instant_prompts = "Indicaciones instantáneas",
        open_sesame = "Ábrete sésamo", btn_door_yeet = "Puerta YEET", entity_alert = "Alerta de entidad",
        fullbright = "Brillo total", no_fog = "Quitar niebla", fov_on = "FOV personalizado", fov = "Campo de visión",
        third_person = "Tercera persona", third_person_dist = "Distancia de la cámara",
        anti_afk = "Anti AFK", auto_rejoin = "Reentrar al ser expulsado", btn_rejoin = "Reentrar al servidor",
        btn_serverhop = "Cambiar de servidor", btn_copy_jobid = "Copiar ID del servidor", btn_copy_join = "Copiar script de entrada",
        btn_reset_char = "Reiniciar personaje",
        anti_desc = "Elimina %s",
        anti_eyefestation = "Anti Eyefestation", anti_pandemonium = "Falsificar Pandemonium",
        anti_pipsqueak = "Falsificar Pipsqueak", anti_a200 = "Falsificar A200", anti_walldweller = "Quitar WallDweller",
        anti_bouncer = "Quitar Bouncer", anti_skeletonhead = "Quitar cabeza de esqueleto", anti_statue = "Quitar estatua",
        anti_nogood = "Anti NoGood", anti_skinless = "Quitar cadáver sin piel", anti_cement = "Quitar zapatos de cemento",
        anti_witchinghour = "Quitar WitchingHour", anti_divine = "Anti DiVine", anti_searchlights = "Quitar reflectores",
        anti_monsterlocker = "Quitar casillero de monstruo", anti_turrets = "Quitar torretas", anti_tripwires = "Quitar cables trampa",
        anti_landmines = "Quitar minas", anti_squiddles = "Anti squiddles", anti_coagulate = "Anti coagulate",
        anti_edentrees = "Quitar Edentrees", anti_damageparts = "Quitar partes de daño", anti_firewall = "Quitar firewall",
        hotkey_fly = "Tecla de vuelo", hotkey_noclip = "Tecla de atravesar", hotkey_esp = "Tecla del ESP", hotkey_panic = "Tecla de pánico",
        n_no_player = "No se encontró ningún jugador", n_anchor_set = "Ancla guardada", n_no_anchor = "No hay ancla guardada",
        n_rooms_missing = "Salas aún no encontradas", n_open_sesame = "Ya puedes atravesar las puertas",
        n_spawned = "¡%s apareció!", n_panic = "Todas las funciones se apagaron", n_no_servers = "No se encontraron otros servidores",
        n_hopping = "Entrando a otro servidor", n_rejoining = "Reentrando",
    },
    ru = {
        pressure_version1 = "1.0.0", pressure_date1 = "2026-10-09", pressure_log1 = "ESP, анти-удаления, движение, автоматизация и инструменты мира для Pressure", pressure_log2 = "Общие Home, Settings, конфиги, фон и переводы",
        tab_visuals = "Визуал", tab_movement = "Движение", tab_automation = "Автоматизация",
        tab_anti = "Анти", tab_world = "Мир", tab_misc = "Прочее",
        sec_esp = "ESP", sec_esp_colors = "Цвета", sec_speed = "Скорость", sec_jump = "Прыжок",
        sec_collision = "Столкновения", sec_flight = "Полёт", sec_teleport = "Телепорт", sec_collect = "Сбор",
        sec_doors = "Двери", sec_alerts = "Оповещения", sec_lighting = "Освещение", sec_camera = "Камера",
        sec_utility = "Утилиты", sec_server = "Сервер", sec_anti_monsters = "Монстры",
        sec_anti_spawns = "Появления", sec_anti_encounters = "Встречи",
        esp = "Включить ESP", esp_d = "Главный переключатель всех опций ESP",
        esp_monsters = "Монстры", esp_players = "Игроки", esp_items = "Предметы", esp_currency = "Валюта",
        esp_keycards = "Карты-ключи", esp_doors = "Выходные двери", esp_lockers = "Шкафчики пустоты",
        esp_fake_doors = "Ложные двери", esp_generators = "Генераторы",
        esp_text = "Подписи", esp_distance = "Показывать расстояние", esp_max_distance = "Макс. расстояние",
        esp_fill = "Прозрачность заливки", color_monster = "Цвет монстров", color_player = "Цвет игроков",
        esp_exit_door = "ВЫХОДНАЯ ДВЕРЬ", esp_locker = "Шкафчик пустоты", esp_fake_door = "ЛОЖНАЯ ДВЕРЬ",
        esp_generator = "Генератор %s%%",
        cframe_speed = "Скорость CFrame", cframe_speed_value = "Значение скорости", speed_boost_on = "Ускорение",
        speed_boost = "Сила ускорения", jumppower_on = "Свой прыжок", jumppower = "Сила прыжка",
        infinite_jump = "Бесконечный прыжок", noclip = "Прохождение сквозь стены", ghost_players = "Призрачные игроки",
        fly = "Полёт", fly_speed = "Скорость полёта",
        btn_tp_nearest = "Телепорт к ближайшему игроку", btn_tp_farthest = "Телепорт к самому дальнему игроку",
        btn_anchor_drop = "Поставить якорь", btn_anchor_beam = "Вернуться к якорю",
        loot_aura = "Аура сбора", loot_radius = "Радиус сбора", instant_prompts = "Мгновенные подсказки",
        open_sesame = "Открой, сезам", btn_door_yeet = "Дверь YEET", entity_alert = "Оповещение о сущностях",
        fullbright = "Полная яркость", no_fog = "Убрать туман", fov_on = "Свой FOV", fov = "Поле зрения",
        third_person = "Третье лицо", third_person_dist = "Расстояние камеры",
        anti_afk = "Анти-AFK", auto_rejoin = "Перезайти после кика", btn_rejoin = "Перезайти на сервер",
        btn_serverhop = "Смена сервера", btn_copy_jobid = "Копировать ID сервера", btn_copy_join = "Копировать скрипт входа",
        btn_reset_char = "Сбросить персонажа",
        anti_desc = "Удаляет %s",
        anti_eyefestation = "Анти Eyefestation", anti_pandemonium = "Подмена Pandemonium",
        anti_pipsqueak = "Подмена Pipsqueak", anti_a200 = "Подмена A200", anti_walldweller = "Убрать WallDweller",
        anti_bouncer = "Убрать Bouncer", anti_skeletonhead = "Убрать череп скелета", anti_statue = "Убрать статую",
        anti_nogood = "Анти NoGood", anti_skinless = "Убрать безкожий труп", anti_cement = "Убрать цементные ботинки",
        anti_witchinghour = "Убрать WitchingHour", anti_divine = "Анти DiVine", anti_searchlights = "Убрать прожекторы",
        anti_monsterlocker = "Убрать шкафчик монстра", anti_turrets = "Убрать турели", anti_tripwires = "Убрать растяжки",
        anti_landmines = "Убрать мины", anti_squiddles = "Анти squiddles", anti_coagulate = "Анти coagulate",
        anti_edentrees = "Убрать Edentrees", anti_damageparts = "Убрать объекты урона", anti_firewall = "Убрать файрвол",
        hotkey_fly = "Клавиша полёта", hotkey_noclip = "Клавиша прохождения", hotkey_esp = "Клавиша ESP", hotkey_panic = "Клавиша паники",
        n_no_player = "Игрок не найден", n_anchor_set = "Якорь поставлен", n_no_anchor = "Якорь не сохранён",
        n_rooms_missing = "Комнаты ещё не найдены", n_open_sesame = "Теперь можно проходить сквозь двери",
        n_spawned = "%s появился!", n_panic = "Все функции выключены", n_no_servers = "Других серверов не найдено",
        n_hopping = "Вход на другой сервер", n_rejoining = "Перезаход",
    },
}
